Chess.WebSite/Controllers/ChessMatchController.cs
using System;
using System.IO;
using System.Security.Claims;
using System.Threading.Tasks;
using Chess.Core.Domain;
using Chess.Infrastructure.Commands;
using Chess.Infrastructure.Services;
using Chess.Infrastructure.Settings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Chess.WebSite.Controllers
{
    [Authorize]
    public class ChessMatchController : WebControllerBase
    {
        private readonly ChessGameSettings _chessGameSettings;
        private readonly IFileProvider _fileProvider;
        private readonly IPlayerService _playerService;
        private readonly UserManager<ApplicationUser> _userManager;
        public ChessMatchController(ICommandDispatcher commandDispatcher,
                                    IOptions<ChessGameSettings> chessGameSettings,
                                    IPlayerService playerService,
                                    UserManager<ApplicationUser> userManager,
                                    IFileProvider fileProvider) : base(commandDispatcher)
        {
            _userManager = userManager;
            _fileProvider = fileProvider;
            _playerService = playerService;
            _chessGameSettings = chessGameSettings.Value;
        }

        public async Task<IActionResult> Index()
        {
            var username = User.FindFirstValue(ClaimTypes.Name);
            var player = await _playerService.GetAsync(username);
            ViewBag.PlayerId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(player);
        }


        public IActionResult ChessGame_copy(Guid id, string duration)
        {
            ViewBag.ChessGameDuration = duration;
            ViewBag.ChessGameId = id;
            return View();
        }
    
        public IActionResult SearchGame(int durationTime){
            //available player list 
            return View();
        }


        public async Task<IActionResult> ChessGameRepeat(string path)
        {
            Console.WriteLine(path);
            var pgn = await _fileProvider.GetFileContent(_chessGameSettings.PGNFilePath,path);
            // ViewBag.pgn = pgn.Replace(System.Environment.NewLine, "");
            ViewBag.pgn = pgn.Replace(System.Environment.NewLine, "\\n");
            // ViewBag.pgn = pgn.Replace(System.Environment.NewLine, " ");
            return View();
        }
    }
}

Chess.WebSite/Controllers/MatchManagementController.cs
using System;
using System.Threading.Tasks;
using Chess.Infrastructure.Commands;
using Chess.Infrastructure.Commands.Match;
using Chess.Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Chess.WebSite.Controllers
{
    public class MatchManagementController : WebControllerBase
    {
  
        private readonly IMatchService _matchService;
        private readonly ILogger _logger;

        public MatchManagementController(IMatchService matchService,
                                            ILoggerFactory loggerFactory,
                                            ICommandDispatcher commandDispatcher) : base(commandDispatcher)
        {
            _logger = loggerFactory.CreateLogger<MatchManagementController>();
            _matchService = matchService;
        }
        
        
        public async Task<IActionResult> MatchListByTournament(Guid tournamentId, MatchMessageId? message = null)
        {
            ViewData["StatusMessage"] =
                message == MatchMessageId.CreateMatchSuccess ? "Mecz utworzony pomyślnie."
                : message == MatchMessageId.UpdateMatchSuccess ? "Mecz aktualizowany pomyślnie."
                : message == MatchMessageId.Error ? "Bład."
                : "";
            ViewBag.Title = "Zarządzanie meczami";
            ViewBag.Message = message;
            var matches = await _matchService.GetByTournamentAsync(tournamentId);
            return View(matches);
        }

        public async Task<IActionResult> MatchListByPlayer(Guid playerId, MatchMessageId? message = null)
        {
            ViewData["StatusMessage"] =
                message == MatchMessageId.CreateMatchSuccess ? "Mecz utworzony pomyślnie."
                : message == MatchMessageId.UpdateMatchSuccess ? "Mecz aktualizowany pomyślnie."
                : message == MatchMessageId.Error ? "Bład."
                : "";
            ViewBag.Title = "Zarządzanie meczami";
            ViewBag.Message = message;
            var matches = await _matchService.GetByPlayerAsync(playerId);
            return View(matches);
        }


        public async Task<IActionResult> MatchListByTournamentRound(Guid tournamentId, int round, MatchMessageId? message = null)
        {

            var parameters = new MatchParameters();
            parameters.TournamentId = tournamentId;  
            parameters.Round = 1;
            var matches = await _matchService.PagedList(parameters);
            return View(matches);
        }




        public async Task<IActionResult> Create(Guid id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromBody]CreateMatch command)
        {
            if(ModelState.IsValid)
            {
                await CommandDispatcher.DispatchAsync(command);
                this.HttpContext.Response.StatusCode = 201;
                _logger.LogInformation(3,"Create tournament successfully");
                return RedirectToAction(nameof(Index), new {Message = MatchMessageId.CreateMatchSuccess});
            }
            return View();
        }


        public async Task<IActionResult> Edit(Guid id)
        {
            id = new Guid("354d9c91-2c45-4ddf-9988-5dce39b39a8f");
            var matchDetails = await _matchService.GetAsync(id);
            if(matchDetails == null)
            {
                return NotFound();
            }
            return View(matchDetails);
        }

        public enum MatchMessageId
        {
            CreateMatchSuccess,
            UpdateMatchSuccess,
            Error
        }
        
    }
}

Chess.WebSite/Views/MatchManagement/Create.cshtml
@using Chess.Infrastructure.Commands.Match
@model CreateMatch

@{
  Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="m-auto" style="width: 70%;">
    <form asp-action="Create">
        <h4>Utwórz mecz</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Nazwa</label>
            <div class="col-sm-10">
                <input asp-for="FirstPlayerUserName" class="form-control" />
                <span asp-validation-for="FirstPlayerUserName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Nazwa</label>
            <div class="col-sm-10">
                <input asp-for="SecondPlayerUserName" class="form-control" />
                <span asp-validation-for="SecondPlayerUserName" class="text-danger"></span>
            </div>
        </div>        

        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Data</label>
            <div class="col-sm-10">
                <input asp-for="BeginAt" type="datetime-local" class="form-control">
                <span asp-validation-for="BeginAt" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Data</label>
            <div class="col-sm-10">
                <input asp-for="DuringTime" type="number" class="form-control">
                <span asp-validation-for="DuringTime" class="text-danger"></span>
            </div>
        </div>
        <button class="btn btn-info btn-block" type="submit">Utwórz</button>
    </form>
</div>

Chess.WebSite/Views/MatchManagement/Edit.cshtml
@using Chess.Infrastructure.DTO
@model MatchDto
@{
  Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@Model.SecondPlayer.UserName
@Model.FirstPlayer.UserName


@Model.Result

Chess.WebSite/Views/MatchManagement/MatchListByTournament.cshtml
@using Chess.Infrastructure.DTO
@model IEnumerable<MatchDto>
@{
  Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="card">
    <div class="card-header">
        Rozegrane partie
    </div>
    <div class="card-body">
        <table class="table">
            <thead class="text-center">
                <tr>
                    <th scope="col">
                        Zawodnicy
                    </th>
                    <th scope="col">
                        Data 
                    </th>
                    <th scope="col">
                        Wynik spotkania
                    </th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody class="text-center"> 
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        <div class="align-content-center">
                            <p >
                                @Html.DisplayFor(modelItem => item.FirstPlayer.UserName) (@Html.DisplayFor(modelItem => item.FirstPlayerRating))
                            </p>
                            <p>
                                VS
                            </p>
                            <p>
                                @Html.DisplayFor(modelItem => item.SecondPlayer.UserName) (@Html.DisplayFor(modelItem => item.SecondPlayerRating))
                            </p>
                        </div>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BeginAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Result)
                    </td>
                    <td>
                        <a asp-controller="ChessMatch" asp-action="ChessGameRepeat" asp-route-path="@item.PgnFileName">
                            <div style="width: 180px;">
                                @await Component.InvokeAsync("ChessBoard",
                                new {
                                    fen = @item.Fen,
                                    boardName = $"board_{@item.Id.ToString()}"
                                })
                            </div>
                        </a>
                        
                    </td>
                    
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Chess.WebSite/Views/MatchManagement/MatchListByTournamentRound.cshtml
@using Chess.Infrastructure.DTO
@model IEnumerable<MatchDto>
@{
  Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card">
    <div class="card-header">
        Rozegrane partie
    </div>
    <div class="card-body">
        <table class="table">
            <thead class="text-center">
                <tr>
                    <th scope="col">
                        Zawodnicy
                    </th>
                    <th scope="col">
                        Data 
                    </th>
                    <th scope="col">
                        Wynik spotkania
                    </th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody class="text-center"> 
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        <div class="align-content-center">
                            <p >
                                @Html.DisplayFor(modelItem => item.FirstPlayer.UserName) (@Html.DisplayFor(modelItem => item.FirstPlayerRating))
                            </p>
                            <p>
                                VS
                            </p>
                            <p>
                                @Html.DisplayFor(modelItem => item.SecondPlayer.UserName) (@Html.DisplayFor(modelItem => item.SecondPlayerRating))
                            </p>
                        </div>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BeginAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Result)
                    </td>
                    <td>
                        <a asp-controller="ChessMatch" asp-action="ChessGameRepeat" asp-route-path="@item.PgnFileName">
                            <div style="width: 180px;">
                                @await Component.InvokeAsync("ChessBoard",
                                new {
                                    fen = @item.Fen,
                                    boardName = $"board_{@item.Id.ToString()}"
                                })
                            </div>
                        </a>
                        
                    </td>
                    
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>