Chess.WebSite/Controllers/ClubController.cs
using System;
using System.Threading.Tasks;
using Chess.Infrastructure.Commands;
using Chess.Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;

namespace Chess.WebSite.Controllers
{
    public class ClubController : WebControllerBase
    {

        
        private readonly IClubService _clubService;
        public ClubController(IClubService clubService,
                                    ICommandDispatcher commandDispatcher
                                    ) : base(commandDispatcher)
        {
            _clubService = clubService;
        }

        public async Task<IActionResult> Index(string message, string status, string searchString)
        {
            ViewBag.StatusCode = status;
            ViewBag.Title = searchString;
            ViewBag.Message = message;

            var a = new ClubParameters();
            a.Name = searchString;


            var clubs = await _clubService.PagedList(a);         
            return View(clubs);
        }

   
        public async Task<IActionResult> Details(Guid clubId)
        {
            var clubDetails = await _clubService.GetAsync(clubId);
            if(clubDetails == null)
            {
                return NotFound();
            }
            return View(clubDetails);
        }
    }
}

Chess.WebSite/Controllers/ClubManagementController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using Chess.Infrastructure.Commands;
using Chess.Infrastructure.Commands.Club;
using Chess.Infrastructure.DTO;
using Chess.Infrastructure.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Chess.WebSite.Controllers
{
    public class ClubManagementController : WebControllerBase
    {
        private readonly IClubService _clubService;
        private readonly ILogger _logger;
        private readonly IWebHostEnvironment webHostEnvironment;  


        public ClubManagementController(IClubService clubService,
                                    ILoggerFactory loggerFactory,
                                    ICommandDispatcher commandDispatcher,
                                    IWebHostEnvironment hostEnvironment
                                    ) : base(commandDispatcher)
        {
            _clubService = clubService;
            _logger = loggerFactory.CreateLogger<ClubManagementController>();
            webHostEnvironment = hostEnvironment;  
        }

        public async Task<IActionResult> Index(string searchString = null, ClubMessageId? message = null)
        {
            ViewData["StatusMessage"] =
                message == ClubMessageId.UpdateClubSuccess ? "Pomyślnie zaktualizowano utworzony pomyślnie."
                : message == ClubMessageId.Error ? "Bład."
                : "";
            ViewBag.Title = "Zarządzaj klubami";
            ViewBag.Message = message;
            
            var a = new ClubParameters();
            a.Name = searchString;


            var clubs = await _clubService.PagedList(a);         
            return View(clubs);
        }


        public async Task<IActionResult> Details(Guid clubId)
        {
            var clubDetails = await _clubService.GetAsync(clubId);
            if(clubDetails == null)
            {
                return NotFound();
            }
            return View(clubDetails);
        }
        public async Task<IActionResult> Edit(string name)
        {
            ViewBag.Title = "Zarządzaj klubami";
            var clubDetails = await _clubService.GetAsync(name);

            if(clubDetails == null)
            {
                return NotFound();
            }
            return View(clubDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ClubDetailsDto clubDetails)
        {
            if(ModelState.IsValid){
                await _clubService.UpdateAsync(clubDetails);
                return RedirectToAction(nameof(Index), new { message = ClubMessageId.UpdateClubSuccess });
            }
            return View(clubDetails);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateClub command)
        {
            if(ModelState.IsValid)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "img", "clubs");  
                command.UploadsFolder = uploadsFolder;
                await CommandDispatcher.DispatchAsync(command);
                this.HttpContext.Response.StatusCode = 201;
                _logger.LogInformation(3,"Create tournament successfully");
                // return RedirectToAction(nameof(Index), new {Message = ClubMessageId.CreateClubSuccess});
            }
            return View();
        }


        public enum ClubMessageId
        {
            CreateClubSuccess,
            UpdateClubSuccess,
            Error
        }
    }
}

Chess.WebSite/Views/ClubManagement/Create.cshtml
@using Chess.Infrastructure.Commands.Club
@model CreateClub

@{
  Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="m-auto p-2" style="width: 70%;">
    <form asp-action="Create" class="m-5" method="post" enctype="multipart/form-data">
        <h4 class="text-center">Utworz nowy klub szachowy</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Nazwa</label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Email kontaktowy</label>
            <div class="col-sm-10">
                <input asp-for="ContactEmail" type="email" class="form-control">
                <span asp-validation-for="ContactEmail" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Obrazek</label>
            <div class="col-sm-10">
                <input asp-for="ProfileImage" type="file" class="form-control"/>
                <span asp-validation-for="ProfileImage" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Informacje</label>
            <div class="col-sm-10">
                <textarea asp-for="Informaction" min="1" max="10" class="form-control"></textarea>
                <span asp-validation-for="Informaction" class="text-danger"></span>
            </div>
        </div>
        @* <div class="col-md-6">  
            <div class="form-group">  
                <label asp-for="ProfileImage" class="control-label"></label>  
                <div class="custom-file">  
                    <input asp-for="ProfileImage" class="custom-file-input" id="customFile">  
                    <label class="custom-file-label" for="customFile">Choose file</label>  
                </div>  
                <span asp-validation-for="ProfileImage" class="text-danger"></span>  
            </div>  
        </div>   *@



        <button class="btn btn-secondary btn-block" type="submit">Zatwierdź</button>
    </form>
</div>
@section scripts{  
    @* <script type="text/javascript">  
        // Add the following code if you want the name of the file appear on select  
        $(".custom-file-input").on("change", function () {  
            var fileName = $(this).val().split("\\").pop();  
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);  
        });  
    </script>   *@
}  

Chess.WebSite/Views/ClubManagement/Details.cshtml
@using Chess.Infrastructure.DTO
@model ClubDetailsDto

@{
  Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="d-flex">
    <a class="p-3" asp-action="Details" asp-route-clubId="@Model.Id"><img class="img img-fluid" src="~/img/clubs/@Model.PictureName" style="width: 300px;"></a>
    <div>
        <div>
            <h1>@Html.DisplayFor(modelItem => Model.Name)</h1>
        </div>
        <div>
            <p>Aktualna liczna członków @Model.PlayersCount</p>      
            <p>Data założenia: @Model.CreatedAt.ToString("MMMM dd, yyyy")</p>                  
        </div>
    </div>
</div>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Szczegółowe informacje</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Klubowicze</a>
  </li>

</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <div class="font-size:2rem">
          @Model.Information
      </div>
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <div class="card">
            <div class="card-body">
            <div>
                @foreach (var item in Model.Players) {
                    <div class="float-left p-2" style="width: 50%;">
                        <div style="width: 400px">
                            @await Html.PartialAsync("_PlayerWithAvatar",item)
                        </div>
                    </div>
                }
            </div>
        </div>
  </div>
 


@* 
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Home</a>
    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Profile</a>
    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Contact</a>
  </div>
</nav>
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">...</div>
  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">...</div>
  <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">...</div>
</div> *@

Chess.WebSite/Views/ClubManagement/Edit.cshtml
@using Chess.Infrastructure.DTO
@model ClubDetailsDto
@{
  Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<form asp-controller="ClubManagement" asp-action="Edit" method="post" class="form-horizontal p-4">
    <h4>@ViewBag.Title</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <div >
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="ContactEmail" class="control-label"></label>
        <div >
            <input asp-for="ContactEmail" class="form-control" />
            <span asp-validation-for="ContactEmail" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Information" class="control-label"></label>
        <div >
            <input asp-for="Information" class="form-control" />
            <span asp-validation-for="Information" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="PictureName" class="control-label"></label>
        <div >
            <input asp-for="PictureName" class="form-control" />
            <span asp-validation-for="PictureName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 text-center">
            <button type="submit" class="btn btn-secondary">Zatwierdź</button>
        </div>
    </div>
</form>

Chess.WebSite/Views/ClubManagement/Index.cshtml
@using Chess.Infrastructure.DTO
@model IEnumerable<ClubDto>

@{
  Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1 class="text-center">@ViewBag.Title</h1>

@if(@ViewBag.StatusCode == "success"){
<h1 class="alert-success">@ViewBag.Message </h1>
}

<a asp-action="Create" class="btn btn-secondary">Stwórz nowy klub</a> 
<form asp-controller="Club" asp-action="Index" method="get" class="m-4">
    <p>
        Szukaj klubu: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>

<div>
    @foreach (var item in Model) {
    <div class="row">
        <div class="d-flex p-2 col-md-6">
            <a asp-action="Details" asp-route-clubId="@item.Id"><img class="img img-fluid " src="~/img/clubs/@item.PictureName" style="width: 150px;"></a>
            <div class="ml-3">
                <div>
                    <h4><a class="text-muted" asp-action="Details" asp-route-clubId="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a></h4>
                </div>
                <div>
                    <span>
                        Aktualna liczna członków @item.PlayersCount | Data utworzenia: @item.CreatedAt.ToString("MMMM dd, yyyy")
                    </span>                        
                </div>
            </div>
        </div>
        <div class="col-md-6 d-flex">
            <div class="m-auto">
                <a class="text-muted" asp-action="SendMessage" asp-route-name="@item.Name"><i class="far fa-envelope fa-2x"></i></a>
            </div>
            <div class="m-auto">
                <a class="text-muted" asp-action="Edit" asp-route-clubId="@item.Id">Edytuj</a> |
                <a class="text-muted" asp-action="Details" asp-route-clubId="@item.Id">Szegóły</a> |
                <a class="text-muted" asp-action="Delete" asp-route-clubId="@item.Id">Usuń</a>
            </div>
        </div>
    </div>
    }
</div>