Chess.WebSite/Controllers/AdminController.cs
using Chess.Infrastructure.Commands;
using Microsoft.AspNetCore.Mvc;

namespace Chess.WebSite.Controllers
{
    public class AdminController : WebControllerBase
    {
        public AdminController(ICommandDispatcher commandDispatcher
                                    ) : base(commandDispatcher)
        {
        }


        public IActionResult Index()
        {
            return View();
        }
        
    }
}

Chess.WebSite/Controllers/ClubController.cs
using System;
using System.Threading.Tasks;
using Chess.Infrastructure.Commands;
using Chess.Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;

namespace Chess.WebSite.Controllers
{
    public class ClubController : WebControllerBase
    {

        
        private readonly IClubService _clubService;
        public ClubController(IClubService clubService,
                                    ICommandDispatcher commandDispatcher
                                    ) : base(commandDispatcher)
        {
            _clubService = clubService;
        }

        public async Task<IActionResult> Index(string message, string status, string searchString)
        {
            ViewBag.StatusCode = status;
            ViewBag.Title = searchString;
            ViewBag.Message = message;

            var a = new ClubParameters();
            a.Name = searchString;


            var clubs = await _clubService.PagedList(a);         
            return View(clubs);
        }

   
        public async Task<IActionResult> Details(Guid clubId)
        {
            var clubDetails = await _clubService.GetAsync(clubId);
            if(clubDetails == null)
            {
                return NotFound();
            }
            return View(clubDetails);
        }
    }
}

Chess.WebSite/Controllers/DrillsController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Chess.Core.Domain.Enum;
using Chess.Infrastructure.Commands;
using Chess.Infrastructure.Services;
using Chess.Infrastructure.Settings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Chess.WebSite.Controllers
{
    public class DrillsController : WebControllerBase
    {
        private readonly IDrillService _drillService;
        private readonly IFileProvider _fileProvider;
        private readonly DrillSettings _drillSettings;
        private readonly DrillAwardService _chessGameAwardService;

        public DrillsController(IDrillService drillService,
                                IFileProvider fileProvider,
                                IOptions<DrillSettings> drillSettings,
                                IAwardImpService chessGameAwardService,
                                ICommandDispatcher commandDispatcher) : base(commandDispatcher)
        {
            _drillSettings = drillSettings.Value;
            _fileProvider = fileProvider;
            _drillService = drillService;
            _chessGameAwardService = (DrillAwardService)chessGameAwardService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetAllCategory()
        {

            return View(CategoryDrillsEnum.GetValues(typeof(CategoryDrillsEnum)));
        }

        public async Task<IActionResult> GetCategoryListElement(string category)
        {
            var drills = await _drillService.GetAllCategoryElementAsync(category);
            return View(drills);
        }

        public async Task<IActionResult> GetChessDrill(Guid? id)
        {
            var drillAward = await _chessGameAwardService.GetAwardDto("konto@gmail.com");
            if(drillAward != null){
                ViewData["awardImgFileName"] = drillAward.FileName;
                ViewData["awardContent"] = drillAward.Comment;
            }

            var drill = id != null ?  await _drillService.GetAsync(id.Value) : await _drillService.GetRandomDrillAsync();
            System.Console.WriteLine(drill.Id);
            var pgn = await _fileProvider.GetFileContent(_drillSettings.FilePath, drill.FileName);
            ViewBag.pgn = pgn.Replace(System.Environment.NewLine, "\\n");

            ViewBag.CorrectlyAttempts = drill.Attempts > 0 ? (100*drill.CorrectlyAttempts)/drill.Attempts : 0;
            return View(drill);
        }

        public async Task<IActionResult> Test()
        {
            var drill = await _drillService.GetDrillAsync();
            return View(drill);
        }



        [HttpPost]
        public async Task SaveDrill(string Result, string DrillId){
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userIdGuid = new Guid(userId);
            var drillIdGuid = new Guid(DrillId);
            DrillResultTypeEnum result = Result == "1" ? DrillResultTypeEnum.CORRECT : DrillResultTypeEnum.INCORRECT;
            await _drillService.AddPlayed(drillIdGuid, userIdGuid, result);
        }
    }

    public enum CategoryDrillsEnum {Gra1, Gra2, Gra3}
    

}

Chess.WebSite/Controllers/MatchController.cs
using System;
using System.Threading.Tasks;
using Chess.Infrastructure.Commands;
using Chess.Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;

namespace Chess.WebSite.Controllers
{
    public class MatchController : WebControllerBase
    {
        private readonly IMatchService _matchService;
        public MatchController( IMatchService matchService,
                                ICommandDispatcher commandDispatcher) : base(commandDispatcher)
        {
            _matchService = matchService;
        }

        public async Task<ActionResult> Index()
        {
            var matches = await _matchService.BrowseAsync();
            return View(matches);
        }


        public async Task<ActionResult> GetPlayerMatch(Guid id)
        {
            var matches = await _matchService.GetByPlayerAsync(id);
            return View(matches);
        }

        public async Task<ActionResult> GetMatchOfTournament()
        {
            var matches = await _matchService.BrowseAsync();
            return View(matches);
        }
        
    }
}

Chess.WebSite/Views/Shared/Components/ChessBoard/ChessBoardViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Chess.WebSite.Views.Shared.Components.ChessBoard
{
    public class ChessBoardViewComponent : ViewComponent
    {
        public ChessBoardViewComponent()
        {
                
        }

        public  IViewComponentResult Invoke(string fen, string boardName)
        {
            ViewBag.BoardName = boardName;
            ViewBag.Fen = fen;
            System.Console.WriteLine(fen);
            return View("ChessboardAsPicture");
        }
    
        // public  IViewComponentResult Invoke(string pgn)
        // {
        //     ViewBag.PGN = pgn;
        //     return View("ChessboardAsRepeatedGame");
        // }
    }
}

Chess.WebSite/Views/Shared/Components/ChessgameList/ChessgameListViewComponent.cs
using System.Threading.Tasks;
using Chess.Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;

namespace Chess.WebSite.Views.Shared.Components.ChessgameList
{
    public class ChessgameListViewComponent : ViewComponent
    {       
        private readonly IMatchService _matchService;
        public ChessgameListViewComponent(IMatchService matchService)
        {
            _matchService = matchService;
        }

        public async Task<IViewComponentResult> InvokeAsync(string card_title)
        {
            ViewBag.CardTitle = card_title;

            var matches = await _matchService.BrowseAsync();
            return View("Default", matches);
        }
    }
}

Chess.WebSite/Views/Shared/Components/Diagram/DiagramViewComponent.cs
using System;
using System.Threading.Tasks;
using Chess.Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Chess.WebSite.Views.Shared.Components.PlayerList
{
    public class DiagramViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string chart_type)
        {
 
            if(chart_type == DiagramTypeEnum.donut.ToString())
            {
                return View("DonutDiagram", chart_type);
            }
            return View("Default", chart_type);
        }


        
        private enum DiagramTypeEnum{
            donut
        }
    }
} 

Chess.WebSite/Views/Shared/Components/MatchList/MatchListViewComponent.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;
using Chess.Infrastructure.DTO;
using Chess.Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;

namespace Chess.WebSite.Views.Shared.Components.MatchList
{
    public class MatchListViewComponent : ViewComponent
    {
        private readonly IMatchService _matchService;
        private IEnumerable<MatchDto> matches;

        public MatchListViewComponent(IMatchService matchService)
        {
            _matchService = matchService;
        }

        public async Task<IViewComponentResult> InvokeAsync(Guid id, string fromTable, bool addChessboard)
        {
            ViewBag.AddChessboard = addChessboard;
            switch(fromTable)
            {
                case "player":
                    matches = await _matchService.GetByPlayerAsync(id);
                    return View("MatchesByPlayer",matches);
                case "tournament":
                    matches = await _matchService.GetByTournamentAsync(id);
                    return View("MatchesByTournament",matches);
                default:
                    return Content("Not found case from matchlist component");
            }
        }
    }
} 

Chess.WebSite/Views/Shared/Components/PlayerList/PlayerListViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Chess.Infrastructure.DTO;
using Chess.Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;

namespace Chess.WebSite.Views.Shared.Components.PlayerList
{
    public class PlayerListViewComponent : ViewComponent
    {
        private readonly IPlayerService _playerService;

        public PlayerListViewComponent(IPlayerService playerService)
        {
            _playerService = playerService;
        }

        public async Task<IViewComponentResult> InvokeAsync(string template, string filter)
        {
            IEnumerable<PlayerDto> players = new List<PlayerDto>();
            switch (filter){
                case "Tournament":
                    var a = new PlayerParameters();
                    players = await _playerService.PagedList(a); 
                break;

                case "PlayerRankingInTournament":
                    var b = new PlayerParameters();
                    players = await _playerService.PagedList(b); 

                break;
            }
            return View("Default", players);
        }
    }
} 

Chess.WebSite/Views/Shared/_AwardComplete.cshtml
@*--> use modal in js:  $("#awardModal").modal(); *@
<div class="container">
  <!-- Modal -->
  <div class="modal fade text-center" id="awardModal" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div>
          <h3 class="modal-title">Gratulacje!! Zdobyłeś nagrodę.</h3>
        </div>

        <div class="modal-body">
            <img class="img img-fluid" src="~/img/awards/@ViewData["awardImgFileName"]" style="width: 200px;">
          <h6>@ViewData["awardContent"]</h6>
        </div>
        <div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
        </div>
      </div>
    </div>
  </div>
</div>

Chess.WebSite/Views/Shared/_Chat.cshtml
<div class="container">
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-2">User</div>
        <div class="col-4"><input type="text" id="userInput" /></div>
    </div>
    <div class="row">
        <div class="col-2">Message</div>
        <div class="col-4"><input type="text" id="messageInput" /></div>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-6">
            <input type="button" id="sendButton" value="Send Message" />
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-6">
        <ul id="messagesList"></ul>
    </div>
</div>
<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>

Chess.WebSite/Views/Shared/_ChessBoard.cshtml
<div>HELLO WORLD</div>

<div id="myBoard" style="width: 400px"></div>
<label>Status:</label>
<div id="status"></div>
<label>FEN:</label>
<div id="fen"></div>
<label>PGN:</label>
<div id="pgn"></div>
<div id="root"></div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<div class="row">
    <div class="col-6">
        <input type="button" id="sendButton" value="Send Message" />
    </div>
</div>
<div class="row">
    <div>Lista ruchów</div>
    <div class="col-6">
        <ul id="movesList"></ul>
    </div>
</div>

Chess.WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TEST</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="https://fonts.googleapis.com/css?family=Dosis:400,700" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/style.css"  />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div>
            <a class="navbar-brand" asp-area="" asp-controller="Article" asp-action="GetPreviewArticles"> <img class="img" style="height: 55px;" src="~/img/test.svg"> Szachy</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="ChessMatch" asp-action="Index">Gra</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Drills" asp-action="GetChessDrill">Zadania szachowe</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Article" asp-action="GetPreviewArticles">Artykuły</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Tournament" asp-action="Index">Turnieje</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Club" asp-action="Index">Kluby</a></li>
            </ul>

            <ul>
            

            @await Html.PartialAsync("_LoginPartial")
        </div>
    </nav>
</header>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
            <div class="col-12 col-md">
                <img class="mb-2" src="/docs/4.5/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
                <small class="d-block mb-3 text-muted">© 2018-2020</small>
            </div>
            <div class="col-6 col-md">
                <h5>Rozrywka</h5>
                <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Graj</a></li>
                <li><a class="text-muted" href="#">Rozwiązuj zadania</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Zasoby</h5>
                <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Kluby</a></li>
                <li><a class="text-muted" href="#">Turnieje</a></li>
                <li><a class="text-muted" href="#">Zadania</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Inne</h5>
                <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Przeglądaj artykuły</a></li>
                </ul>
            </div>
            </div>
        </footer>
    </div>
    
@if (@ViewData["awardContent"] != null)
{
    @await Html.PartialAsync("_AwardComplete")
}
@await Html.PartialAsync("_PGNModal")

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        @* <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script> *@
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        @* https://fontawesome.com/start *@
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
        @* <script src="https://use.fontawesome.com/2321be0ad8.js"></script> *@
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.3.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>


@* https://svg-clipart.com/search.php?q=puzzle *@

Chess.WebSite/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TEST</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="https://fonts.googleapis.com/css?family=Dosis:400,700" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/style.css"  />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div>
            <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index"> <img class="img" style="height: 55px;" src="~/img/test.svg"> Szachy - Panel administracyjny</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="TournamentManagement" asp-action="Index">Zarządzaj turniejami</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="ClubManagement" asp-action="Index">Zarządzaj klubami</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="ArticleManagement" asp-action="Index">Zarządzaj arykułami</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="PlayerManagement" asp-action="Index">Zarządzaj użytkownikami</a></li>
            </ul>
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </nav>
</header>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
            <div class="col-12 col-md">
                <img class="mb-2" src="/docs/4.5/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
                <small class="d-block mb-3 text-muted">© 2018-2020</small>
            </div>
            <div class="col-6 col-md">
                <h5>Turnieje</h5>
                <ul class="list-unstyled text-small">
                <li><a class="text-muted" asp-area="" asp-controller="TournamentManagement" asp-action="Create">Utwórz</a></li>
                <li><a class="text-muted" asp-area="" asp-controller="TournamentManagement" asp-action="Index">Przeglądaj</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Klub</h5>
                <ul class="list-unstyled text-small">
                <li><a class="text-muted" asp-area="" asp-controller="ClubManagement" asp-action="Create">Utwórz</a></li>
                <li><a class="text-muted" asp-area="" asp-controller="ClubManagement" asp-action="Index">Przeglądaj</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Artykuły</h5>
                <ul class="list-unstyled text-small">
                <li><a class="text-muted" asp-area="" asp-controller="ArticleManagement" asp-action="Create">Utwórz</a></li>
                <li><a class="text-muted" asp-area="" asp-controller="ArticleManagement" asp-action="Index">Przeglądaj</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Użytkownicy</h5>
                <ul class="list-unstyled text-small">
                <li><a class="text-muted" asp-area="" asp-controller="PlayerManagement" asp-action="Index">Przeglądaj</a></li>
                </ul>
            </div>
            </div>
        </footer>
    </div>

@await Html.PartialAsync("_AwardComplete")
@await Html.PartialAsync("_PGNModal")

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        @* <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script> *@
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        @* https://fontawesome.com/start *@
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
        @* <script src="https://use.fontawesome.com/2321be0ad8.js"></script> *@
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.3.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>


@* https://svg-clipart.com/search.php?q=puzzle *@

Chess.WebSite/Views/Shared/_PGNModal.cshtml
<div class="container ">
    <!-- Modal -->
    <div class="modal fade text-center" id="PGNModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content ">
        <div>
            <h3 class="modal-title border-bottom p-3">PGN</h3>
        </div>
 
        <div class="modal-body bg-light ">
              <div class="form-group">
                <label>FEN</label>
                <input type="tekst" class="form-control" id="fenInPgnModal">
              </div>
              <div class="form-group">
                <label>PGN</label>
                <textarea type="tekst" class="form-control" rows=10 id="pgnInPgnModal"></textarea>
              </div>
        </div>
    </div>
</div>

Chess.WebSite/Views/Shared/_PlayerWithAvatar.cshtml
@using Chess.Infrastructure.DTO
@model PlayerDto

<div class="d-flex">
    <div style="max-width:30%; height: auto">
        <a asp-controller="Member" asp-action="Index" asp-route-username="@Model.UserName"><img class="img img-fluid img-thumbnail" style="max-width: 100%; height: auto" src="~/img/@Model.AvatarImageName"></a>
    </div>
    <div class="pl-2">
        <div>
            <span><a asp-controller="Member" asp-action="Index" asp-route-username="@Model.UserName">@Html.DisplayFor(modelItem => Model.UserName)</a></span>
            <span>(@Html.DisplayFor(modelItem => Model.RatingElo))</span>
        </div>
    </div>
</div>

Chess.WebSite/Views/Shared/_PlayersInTournament.cshtml
@using Chess.Infrastructure.DTO
@model TournamentDetailsDto



<table class="table">
    <thead>
        <tr>
            <th>
                Nazwa zawodnika
            </th>
            <th>
                Punkty rankingowe gracza
            </th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Players) {
        <tr>
            <td>
                <a asp-controller="Member" asp-action="Index" asp-route-username="@item.UserName">@Html.DisplayFor(modelItem => item.UserName)</a>
            </td>
            <th class="text-center">
               
            </th>
        </tr>
}
    </tbody>
</table>

Chess.WebSite/Views/Shared/_SmallPlayerInfo.cshtml
@using Chess.Infrastructure.DTO
@model PlayerDto

<div>
    <div class="mr-2 float-left">
        <img src="https://unsplash.it/35/35">
    </div>
    <div>
        <div><a asp-controller="Match" asp-action="GetPlayerMatch" asp-route-id="@Model.PlayerId">@Html.DisplayFor(modelItem => Model.UserName)</a> <img src="https://unsplash.it/20/20"></div>
        <span>(2133)</span>
    </div>
</div>