Chess.WebSite/Controllers/TournamentController.cs
using System;
using System.Threading.Tasks;
using Chess.Core.Domain;
using Chess.Core.Domain.Enum;
using Chess.Infrastructure.Commands;
using Chess.WebSite.Controllers;
using Microsoft.AspNetCore.Mvc;

namespace Chess.Infrastructure.Services
{
    public class TournamentController : WebControllerBase
    {

        private readonly ITournamentService _tournamentService;
        private readonly IManageTournamentService _manageTournamentService;

        public TournamentController(ITournamentService tournamentService,
                                    IManageTournamentService manageTournamentService,
                                    ICommandDispatcher commandDispatcher
                                    ) : base(commandDispatcher)
        {
            _tournamentService = tournamentService;
            _manageTournamentService = manageTournamentService;
        }

        public async Task<IActionResult> Index(string message, string status, string searchString)
        {
            ViewBag.Title = "Turnieje";

            ViewBag.StatusCode = status;
            ViewBag.Message = message;
            var parameters = new TournamentParameters();
            parameters.Name = searchString;
            parameters.Status  = TournamentStatusEnum.created; 
            var tournaments = await _tournamentService.PagedList(parameters);         
            return View(tournaments);
        }




        public async Task<IActionResult> CompletedTournament()
        {
            ViewBag.Title = "Zakończone turnieje";
            
            var parameters = new TournamentParameters();
            parameters.Status  = TournamentStatusEnum.complete; 
            var tournaments = await _tournamentService.PagedList(parameters);   

            return View(tournaments);
        }





   
        public async Task<IActionResult> Details(Guid tournamentId)
        {
            var tournamentDetails = await _tournamentService.GetAsync(tournamentId);
            if(tournamentDetails == null)
            {
                return NotFound();
            }
            return View(tournamentDetails);
        }


        public async Task<IActionResult> CompletedTournamentDetails(Guid tournamentId)
        {
            var tournamentDetails = await _tournamentService.GetAsync(tournamentId);
            if(tournamentDetails == null)
            {
                return NotFound();
            }
            return View(tournamentDetails);
        }

        public async Task<IActionResult> Join(Guid tournamentId)
        {
            await _manageTournamentService.AddPlayerToTournament(tournamentId, this.User.Identity.Name);
            return NoContent();
            // return RedirectToAction("Details");P
        }

        // private void SearchByName(ref IEnumerable<TournamentDto> tournaments, string ownerName)
        // {
        //     if (!tournaments.Any() || string.IsNullOrWhiteSpace(ownerName))
        //         return;

        //     tournaments = tournaments.Where(o => o.Name.ToLower().Contains(ownerName.Trim().ToLower()));
        //     }
        }
}

Chess.WebSite/Controllers/TournamentManagementController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Chess.Infrastructure.Commands;
using Chess.Infrastructure.Commands.Message;
using Chess.Infrastructure.Commands.Tournament;
using Chess.Infrastructure.DTO;
using Chess.Infrastructure.EF;
using Chess.Infrastructure.Services;
using Chess.Infrastructure.Settings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace Chess.WebSite.Controllers
{
    // [Authorize(Roles="Admin")]
    public class TournamentManagementController : WebControllerBase
    {
        private readonly ITournamentService _tournamentService;
        private readonly ILogger _logger;

        public TournamentManagementController(ITournamentService tournamentService,
                                            ILoggerFactory loggerFactory,
                                            ICommandDispatcher commandDispatcher) : base(commandDispatcher)
        {
            _logger = loggerFactory.CreateLogger<TournamentManagementController>();
            _tournamentService = tournamentService;
        }
    // ITournamentService tournamentService,
    // public TournamentController(
    //     ICommandDispatcher commandDispatcher) : base(commandDispatcher)
    // {
    //     // _tournamentService = tournamentService;
    // }

    // [HttpGet]
        public async Task<IActionResult> Index(TournamentMessageId? message = null)
        {
            ViewData["StatusMessage"] =
                message == TournamentMessageId.CreateTournamentSuccess ? "Turniej utworzony pomyślnie."
                : message == TournamentMessageId.Error ? "Bład."
                : "";
            ViewBag.Title = "Zarządzaj turniejami";
            ViewBag.Message = message;
            var tournament = await _tournamentService.BrowseAsync();

            return View(tournament);
        }

        public async Task<IActionResult> Details(string name)
        {
            var tournamentDetails = await _tournamentService.GetAsync(name);
            if(tournamentDetails == null)
            {
                return NotFound();
            }
            return View(tournamentDetails);
        }
        public async Task<IActionResult> Edit(string name)
        {
            var tournamentDetails = await _tournamentService.GetAsync(name);
            if(tournamentDetails == null)
            {
                return NotFound();
            }
            return View(tournamentDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TournamentDetailsDto tournamentDetails)
        {
            if(ModelState.IsValid){
                await _tournamentService.UpdateAsync(tournamentDetails);
                return RedirectToAction(nameof(Index), new { message = TournamentMessageId.UpdateTournamentSuccess });
            }
            return View(tournamentDetails);
        }

        public IActionResult Create()
        {
            ViewBag.Information = "Create new tournament";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateTournament command)
        {
            if(ModelState.IsValid)
            {
                await CommandDispatcher.DispatchAsync(command);
                this.HttpContext.Response.StatusCode = 201;
                _logger.LogInformation(3,"Create tournament successfully");
                return RedirectToAction(nameof(Index), new {Message = TournamentMessageId.CreateTournamentSuccess});
            }
            return View();
        }


        public ActionResult GetTournament(){
            return View();
        }



        public async Task<IActionResult> SendMessage(string name)
        {
            ViewBag.TournamentName = name;
            var tournament = await _tournamentService.GetAsync(name);
            if(tournament == null)
            {
                return NotFound();
            }
            ViewBag.PlayersDropDown = new MultiSelectList(tournament.Players,"Email","UserName",tournament.Players.Select(x => x.Email));
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendMessage(SendMessage command)
        {
            if(ModelState.IsValid)
            {
                await CommandDispatcher.DispatchAsync(command);
            }
            else
            {
                throw new Exception("No input parameter");
            }
            return RedirectToAction("Index");
        }
        public enum TournamentMessageId
        {
            CreateTournamentSuccess,
            UpdateTournamentSuccess,
            Error
        }
    }
}

Chess.WebSite/Views/TournamentManagement/Create.cshtml
@using Chess.Infrastructure.Commands.Tournament
@model CreateTournament

@{
  Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="m-auto p-2" style="width: 70%;">
    <form asp-action="Create" class="m-5">
        <h4 class="text-center">Utworz nowy turniej</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Nazwa</label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        @* <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Nazwa Klubu</label>
            <div class="col-sm-10">
                <select asp-for="ClubName" class="custom-select">
                    <option value="">Wybierz klub</option>
                    <option value="a">Wszystkie</option>
                    <option value="a">AA</option>
                    <option value="b">BB</option>
                </select>
                <span asp-validation-for="GameTyp" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Typ</label>
            <div class="col-sm-10">
                <select asp-for="GameTyp" class="custom-select">
                    <option value="">Wybierz typ gry</option>
                    <option value="standard">Standard</option>
                    <option value="ranked">Ranked</option>
                </select>
                <span asp-validation-for="GameTyp" class="text-danger"></span>
            </div>
        </div> *@
        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Data</label>
            <div class="col-sm-10">
                <input asp-for="StartEvent" type="datetime-local" class="form-control">
                <span asp-validation-for="StartEvent" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Liczba rund</label>
            <div class="col-sm-10">
                <input asp-for="RoundAmount" type="number" min="1" max="10" class="form-control">
                <span asp-validation-for="RoundAmount" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Liczba uczestników</label>
            <div class="col-sm-5">
                <input asp-for="MinPlayers" class="form-control" />
                <span asp-validation-for="MinPlayers" class="text-danger"></span>
            </div>
            <div class="col-sm-5">
                <input asp-for="MaxPlayers" class="form-control" />
                <span asp-validation-for="MaxPlayers" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label control-label">Ranking</label>
            <div class="col-sm-5">
                <input asp-for="MinRank" class="form-control" />
                <span asp-validation-for="MinRank" class="text-danger"></span>
            </div>
            <div class="col-sm-5">
                <input asp-for="MaxRank" class="form-control" />
                <span asp-validation-for="MaxRank" class="text-danger"></span>
            </div>
        </div>

        <button class="btn btn-secondary btn-block" type="submit">Utwórz</button>
    </form>
</div>

Chess.WebSite/Views/TournamentManagement/Details.cshtml
@using Chess.Infrastructure.DTO
@model TournamentDetailsDto

@{
  Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item active">
    <a class="nav-link " id="pills-information-tab" data-toggle="pill" href="#pills-information" role="tab" aria-controls="pills-information" aria-selected="true">Informacje</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" id="pills-players-tab" data-toggle="pill" href="#pills-players" role="tab" aria-controls="pills-players" aria-selected="false">Uczestnicy</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" id="pills-matches-tab" data-toggle="pill" href="#pills-matches" role="tab" aria-controls="pills-matches" aria-selected="false">Mecze</a>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-information" role="tabpanel" aria-labelledby="pills-information-tab">
    <div class="card">
        <div class="card-header">
            Informacje o turnieju
        </div>
        <div class="card-body">
            <table class="table">
                <tbody>
                    <tr>
                        <th scope="row">Nazwa turnieju</th>
                        <td>@Model.Name</td>
                    </tr>
                    <tr>
                        <th scope="row">Data rozpoczęcia</th>
                        <td>@Model.StartEvent.ToString("dd MMMM yyyy")</td>
                    </tr>
                    <tr>
                        <th scope="row">Godzina rozpoczęcia</th>
                        <td>@Model.StartEvent.ToString("H:mm")</td>
                    </tr>
                    <tr>
                        <th scope="row">Maksymalna ilość graczy</th>
                        <td>@Model.MinPlayers - @Model.MaxPlayers</td>
                    </tr>
                    <tr>
                        <th scope="row">Liczba zgraczy zapisana na turniej</th>
                        <td>@Model.RegisteredPlayersCount</td>
                    </tr>
                    <tr>
                        <th scope="row">Dopuszczalny ranking graczy</th>
                        <td>@Model.MinRank - @Model.MaxRank</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
  </div>
  <div class="tab-pane fade" id="pills-players" role="tabpanel" aria-labelledby="pills-players-tab">
    <div class="card">
        <div class="card-header">
            Zapisanie gracze
        </div>
        <div class="card-body">
            @await Html.PartialAsync("_PlayersInTournament")
        </div>
    </div>
  </div>
  <div class="tab-pane fade" id="pills-matches" role="tabpanel" aria-labelledby="pills-matches-tab">
   @await Component.InvokeAsync("MatchList",
    new {
        id = @Model.Id,
        fromTable = "tournament",
        addChessboard = false
    })
  </div>
</div>

Chess.WebSite/Views/TournamentManagement/Edit.cshtml
@using Chess.Infrastructure.DTO
@model TournamentDetailsDto

@{
  Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<form asp-controller="TournamentManagement" asp-action="Edit" method="post" class="form-horizontal p-4">
    <h4>Zarządzaj informacjami o turnieju</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <div >
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="StartEvent" class="control-label"></label>
        <div >
            <input asp-for="StartEvent" class="form-control" />
            <span asp-validation-for="StartEvent" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="MinRank" class="control-label"></label>
        <div class="">
            <input asp-for="MinRank" class="form-control" />
            <span asp-validation-for="MinRank" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="MaxRank" class=" control-label"></label>
        <div class="">
            <input asp-for="MaxRank" class="form-control" />
            <span asp-validation-for="MaxRank" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="MinPlayers" class=" control-label"></label>
        <div >
            <input asp-for="MinPlayers" class="form-control" />
            <span asp-validation-for="MinPlayers" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="MaxPlayers" class="control-label"></label>
        <div>
            <input asp-for="MaxPlayers" class="form-control" />
            <span asp-validation-for="MaxPlayers" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 text-center">
            <button type="submit" class="btn btn-secondary btn-block">Zatwierdź</button>
        </div>
    </div>
</form>

Chess.WebSite/Views/TournamentManagement/Index.cshtml
@using Chess.Infrastructure.DTO
@model IEnumerable<TournamentDto>

@{
  Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1 class="text-center">@ViewBag.Title</h1>

@if(@ViewBag.StatusCode == "success"){
<h1 class="alert-success">@ViewBag.Message </h1>
}

<!-- Tournaments -->

<a asp-action="Create" class="btn btn-secondary">Stwórz nowy turniej</a> 
<form asp-controller="Tournament" asp-action="Index" method="get" class="m-4">
    <p>
        Turniej: <input type="text" name="SearchString">
        <input type="submit" value="Szukaj" />
    </p>
</form>
<table class="table text-center">
    <thead>
        <tr>
            <th class="text-left">
                @Html.DisplayNameFor(model => model.Name) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxPlayers)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegisteredPlayersCount)
            </th>
            <th class="text-center">
                Wyślij wiadomość
            </th>
            <th></th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
        <tr>
            <td class="text-left">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxPlayers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegisteredPlayersCount)
            </td>
            <td class="text-center">
                <a asp-action="SendMessage" asp-route-name="@item.Name"><i class="far fa-envelope fa-2x"></i></a>
            </td>
            <td>
                <a asp-action="Edit" asp-route-name="@item.Name">Edytuj</a> |
                <a asp-action="Details" asp-route-name="@item.Name">Szegóły</a> |
                <a asp-action="Delete" asp-route-name="@item.Name">Usuń</a>
            </td>
        </tr>
}
    </tbody>
</table>

Chess.WebSite/Views/TournamentManagement/SendMessage.cshtml
@model Chess.Infrastructure.Commands.Message.SendMessage
<link href="~/lib/chosen/css/chosen.min.css" rel="stylesheet" />
@{
  Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<area class="container">
    <h1 class="text-center">Wyślij wiadomość do użytkowników turnieju: @ViewBag.TournamentName</h1>
    <div class="row">
        <div class="col-10 m-auto">
            <form asp-action="SendMessage">
                <div class="form-group">
                    <label>Do</label>
                    <select multiple="multiple"
                            asp-for="@Model.SendToList" 
                            asp-items="ViewBag.PlayersDropDown"
                            id="multiSelectList"
                            >
                    </select>
                <div>
                <div class="form-group">
                    <label>Temat</label>
                    <input asp-for="Title" type="text" min="1" max="100" class="form-control">
                    <span asp-validation-for="Title" class="text-danger"></span>
                <div>
                <div class="form-group">
                    <label>Treść wiadomości</label>
                    <textarea asp-for="Content" type="text" class="form-control" rows="6"></textarea>
                    <span asp-validation-for="Content" class="text-danger"></span>                    
                </div>
                <div class="form-group">
                    <button class="btn btn-secondary btn-block" type="submit">Wyślij</button>
                </div>
            </form>
        </div>
    </div>
</article>


@section Scripts {
    <script src="~/lib/chosen/js/chosen.jquery.min.js"></script>
    <script>
        $(function(){
            $("#multiSelectList").chosen(
                    {width: "100%"})
        });
    </script>
}